"""
engines/report_engine.py

Report Engine - Medical ERP V2

Project rule: "Keep business logic inside the Engine only." This is the
ONLY place that:
    - resolves a report_definition's applicable_filters into a
      complete, bound parameter dict (missing optional filters filled
      with None) before calling ReportQueryExecutor.run()
    - applies the confirmed Report Data Rules (Posted-only, Cancelled-
      excluded, Draft-excluded) as a SHARED helper -- individual
      report_definition.sql_template rows still write their own
      `status = 'Posted'` clause (see note below), but this Engine is
      where that RULE is documented and where a future
      "reconciliation" cross-check against it lives
    - checks permission (including the extra financial-statement gate)
      before running anything
    - computes Management Dashboard widget values
    - powers the Master Search bar (report names + delegates to
      per-module search, see get_master_search_results())
    - runs the four confirmed Reconciliation Exception checks
    - builds export metadata (Company/Branch/Report Name/Date Range/
      Generated By/Generated At/Filters Used)
"""

from __future__ import annotations

import logging
from dataclasses import dataclass
from datetime import date, datetime
from typing import Any, Optional

from engines.exceptions import RecordNotFoundError, ValidationError
from engines.report_validator import STANDARD_FILTERS, ReportValidator
from models.management_dashboard_model import ManagementDashboardModel
from models.report_definition_model import ReportDefinitionModel
from models.report_permission_model import ReportPermissionModel
from models.report_query_executor import ReportQueryExecutor

logger = logging.getLogger(__name__)


@dataclass
class ReportResultDTO:
    report_code: str
    report_name: str
    columns_definition: list[dict]
    rows: list[dict]
    drill_down_report_code: Optional[str]
    drill_down_source_type: Optional[str]
    filters_used: dict[str, Any]
    generated_at: datetime


class ReportEngine:
    """Business-rule orchestration for the Reports module."""

    def __init__(
        self,
        definition_model: Optional[ReportDefinitionModel] = None,
        dashboard_model: Optional[ManagementDashboardModel] = None,
        permission_model: Optional[ReportPermissionModel] = None,
        executor: Optional[ReportQueryExecutor] = None,
        validator: Optional[ReportValidator] = None,
        # Cross-module search delegates -- each is a callable the
        # Screen layer wires in (search_threads-style functions already
        # built in every prior module's Model, e.g.
        # SaleInvoiceModel.search, CustomerModel.search, ...). Optional
        # so this Engine has no HARD dependency on every other module.
        search_delegates: Optional[dict[str, Any]] = None,
    ) -> None:
        self._definition_model = definition_model or ReportDefinitionModel()
        self._dashboard_model = dashboard_model or ManagementDashboardModel()
        self._permission_model = permission_model or ReportPermissionModel()
        self._executor = executor or ReportQueryExecutor()
        self._validator = validator or ReportValidator()
        self._search_delegates = search_delegates or {}

    # ------------------------------------------------------------------ #
    # RUN A REPORT
    # ------------------------------------------------------------------ #
    def run_report(self, report_code: str, filters: dict[str, Any], user_role: str) -> ReportResultDTO:
        definition = self._definition_model.get_by_code(report_code)
        if definition is None:
            raise RecordNotFoundError(f"Report '{report_code}' not found.")

        granted = self._permission_model.get_permissions_for_role(user_role)
        permission_result = self._validator.validate_permission(
            definition["required_permission"], granted, definition["is_financial_statement"]
        )
        if not permission_result.is_valid:
            raise ValidationError("; ".join(permission_result.errors))

        applicable = list(definition["applicable_filters"])
        keys_result = self._validator.validate_filter_keys(applicable, set(filters.keys()))
        if not keys_result.is_valid:
            raise ValidationError("; ".join(keys_result.errors))

        date_result = self._validator.validate_date_range(filters.get("date_from"), filters.get("date_to"))
        if not date_result.is_valid:
            raise ValidationError("; ".join(date_result.errors))

        # Fill every STANDARD_FILTERS key the template's placeholders
        # might reference with None if the caller didn't supply it --
        # the sql_template's own "%(x)s IS NULL OR ..." pattern (see
        # Part 1's seed examples) handles an unset filter as "no filter".
        bound_params = {key: filters.get(key) for key in STANDARD_FILTERS}

        rows = self._executor.run(definition["sql_template"], bound_params)

        return ReportResultDTO(
            report_code=definition["report_code"],
            report_name=definition["report_name"],
            columns_definition=definition["columns_definition"],
            rows=rows,
            drill_down_report_code=definition["drill_down_report_code"],
            drill_down_source_type=definition["drill_down_source_type"],
            filters_used={k: v for k, v in filters.items() if v is not None},
            generated_at=datetime.now(),
        )

    # ------------------------------------------------------------------ #
    # MANAGEMENT DASHBOARD
    # ------------------------------------------------------------------ #
    def get_management_dashboard(self, filters: dict[str, Any]) -> list[dict[str, Any]]:
        """
        Runs every active management_dashboard_widget's sql_template and
        returns [{"widget_code", "widget_name", "widget_type", "data": rows}, ...].
        Every widget shares the same filter-binding approach as
        run_report() -- no permission gate here since the Management
        Dashboard's OWN screen-level visibility is a simpler, coarser
        check (Screens layer), not per-widget.
        """
        bound_params = {key: filters.get(key) for key in STANDARD_FILTERS}
        widgets = self._dashboard_model.list_active_widgets()
        results = []
        for widget in widgets:
            data = self._executor.run(widget["sql_template"], bound_params)
            results.append({
                "widget_code": widget["widget_code"],
                "widget_name": widget["widget_name"],
                "widget_type": widget["widget_type"],
                "data": data,
            })
        return results

    # ------------------------------------------------------------------ #
    # MASTER SEARCH
    # ------------------------------------------------------------------ #
    def get_master_search_results(self, search_text: str) -> dict[str, list[dict]]:
        """
        Returns {"reports": [...], "<delegate_key>": [...], ...}. Report
        NAME matching is this Engine's own job
        (ReportDefinitionModel.search_by_name()). Matching an invoice
        number / customer / item / account / journal number etc. is
        NOT reimplemented here -- each already has a working `search()`
        method on its own Model from its own module (SaleInvoiceModel,
        CustomerModel, ItemModel, ChartOfAccountsModel, JournalModel,
        ...). This Engine calls whichever of those were wired in via
        `search_delegates` at construction time, so the Master Search
        bar is a thin aggregator, never a second copy of any module's
        search logic (confirmed project rule: never duplicate).
        """
        results: dict[str, list[dict]] = {
            "reports": self._definition_model.search_by_name(search_text)
        }
        for key, delegate_fn in self._search_delegates.items():
            try:
                results[key] = delegate_fn(search_text)
            except Exception:
                logger.exception("Master Search delegate '%s' failed; omitting its results.", key)
                results[key] = []
        return results

    # ------------------------------------------------------------------ #
    # RECONCILIATION EXCEPTIONS -- the four confirmed live checks
    # ------------------------------------------------------------------ #
    def check_trial_balance_exception(self, date_from: date, date_to: date) -> Optional[dict]:
        """Debit != Credit across all Posted journal lines in range -> exception."""
        sql = """
            SELECT COALESCE(SUM(jel.debit_amount), 0) AS total_debit,
                   COALESCE(SUM(jel.credit_amount), 0) AS total_credit
            FROM journal_entry_line jel
            JOIN journal_entry je ON je.journal_entry_id = jel.journal_entry_id
            WHERE je.status = 'Posted' AND je.is_deleted = FALSE
              AND je.journal_date_ad BETWEEN %(date_from)s AND %(date_to)s;
        """
        row = self._executor.run(sql, {"date_from": date_from, "date_to": date_to})[0]
        debit, credit = float(row["total_debit"]), float(row["total_credit"])
        if round(debit, 2) != round(credit, 2):
            return {"check": "Trial Balance", "total_debit": debit, "total_credit": credit, "difference": round(debit - credit, 2)}
        return None

    def check_stock_exception(self, item_batch_id: int, opening_qty: float,
                               date_from: date, date_to: date) -> Optional[dict]:
        """Opening + IN - OUT != Closing (per batch, from existing stock_ledger) -> exception."""
        sql = """
            SELECT COALESCE(SUM(quantity_change) FILTER (WHERE quantity_change > 0), 0) AS total_in,
                   COALESCE(SUM(quantity_change) FILTER (WHERE quantity_change < 0), 0) AS total_out
            FROM stock_ledger
            WHERE item_batch_id = %(item_batch_id)s
              AND transaction_date_ad BETWEEN %(date_from)s AND %(date_to)s;
        """
        row = self._executor.run(sql, {"item_batch_id": item_batch_id, "date_from": date_from, "date_to": date_to})[0]
        total_in, total_out = float(row["total_in"]), float(row["total_out"])
        expected_closing = opening_qty + total_in + total_out  # total_out is already negative
        # Actual current qty is read from item_batch.current_qty (existing Item Module column)
        actual_sql = "SELECT current_qty FROM item_batch WHERE item_batch_id = %(item_batch_id)s;"
        actual_row = self._executor.run(actual_sql, {"item_batch_id": item_batch_id})[0]
        actual_closing = float(actual_row["current_qty"])
        if round(expected_closing, 2) != round(actual_closing, 2):
            return {"check": "Stock", "item_batch_id": item_batch_id, "expected_closing": expected_closing,
                    "actual_closing": actual_closing, "difference": round(expected_closing - actual_closing, 2)}
        return None

    def check_receivable_exception(self, customer_id: int, opening_balance: float,
                                    date_from: date, date_to: date) -> Optional[dict]:
        """Opening + Sales - Receipt +/- Adjustments (Sale Return) != live outstanding -> exception."""
        sql = """
            SELECT
                COALESCE((SELECT SUM(grand_total) FROM sale_invoice
                          WHERE customer_id = %(customer_id)s AND status = 'Posted'
                            AND invoice_date_ad BETWEEN %(date_from)s AND %(date_to)s), 0) AS total_sales,
                COALESCE((SELECT SUM(ra.allocated_amount) FROM receipt_allocation ra
                          JOIN receipt r ON r.receipt_id = ra.receipt_id
                          JOIN sale_invoice si ON si.sale_invoice_id = ra.sale_invoice_id
                          WHERE si.customer_id = %(customer_id)s AND r.status != 'Cancelled'
                            AND r.receipt_date_ad BETWEEN %(date_from)s AND %(date_to)s), 0) AS total_receipts,
                COALESCE((SELECT SUM(grand_total) FROM sale_return
                          WHERE customer_id = %(customer_id)s AND status = 'Posted'
                            AND refund_mode = 'Adjust Against Invoice'
                            AND return_date_ad BETWEEN %(date_from)s AND %(date_to)s), 0) AS total_adjustments
        """
        row = self._executor.run(sql, {"customer_id": customer_id, "date_from": date_from, "date_to": date_to})[0]
        expected_closing = opening_balance + float(row["total_sales"]) - float(row["total_receipts"]) - float(row["total_adjustments"])
        # Actual closing = live outstanding sum, same computation ReceiptModel already exposes per-invoice
        outstanding_sql = """
            SELECT COALESCE(SUM(si.grand_total
                - COALESCE(ra_sum.total_allocated, 0) - COALESCE(sr_sum.total_adjusted, 0)), 0) AS actual_outstanding
            FROM sale_invoice si
            LEFT JOIN (SELECT ra.sale_invoice_id, SUM(ra.allocated_amount) AS total_allocated
                       FROM receipt_allocation ra JOIN receipt r ON r.receipt_id = ra.receipt_id
                       WHERE r.status != 'Cancelled' GROUP BY ra.sale_invoice_id) ra_sum
                ON ra_sum.sale_invoice_id = si.sale_invoice_id
            LEFT JOIN (SELECT sale_invoice_id, SUM(grand_total) AS total_adjusted FROM sale_return
                       WHERE refund_mode = 'Adjust Against Invoice' AND status != 'Cancelled'
                       GROUP BY sale_invoice_id) sr_sum ON sr_sum.sale_invoice_id = si.sale_invoice_id
            WHERE si.customer_id = %(customer_id)s AND si.status = 'Posted';
        """
        actual_row = self._executor.run(outstanding_sql, {"customer_id": customer_id})[0]
        actual_closing = float(actual_row["actual_outstanding"])
        if round(expected_closing, 2) != round(actual_closing, 2):
            return {"check": "Receivable", "customer_id": customer_id, "expected_closing": expected_closing,
                    "actual_closing": actual_closing, "difference": round(expected_closing - actual_closing, 2)}
        return None

    def check_payable_exception(self, supplier_id: int, opening_balance: float,
                                 date_from: date, date_to: date) -> Optional[dict]:
        """Mirrors check_receivable_exception() exactly, supplier/purchase side."""
        sql = """
            SELECT
                COALESCE((SELECT SUM(grand_total) FROM purchase_invoice
                          WHERE supplier_id = %(supplier_id)s AND status = 'Posted'
                            AND invoice_date_ad BETWEEN %(date_from)s AND %(date_to)s), 0) AS total_purchases,
                COALESCE((SELECT SUM(pa.allocated_amount) FROM payment_allocation pa
                          JOIN payment p ON p.payment_id = pa.payment_id
                          JOIN purchase_invoice pi ON pi.purchase_invoice_id = pa.purchase_invoice_id
                          WHERE pi.supplier_id = %(supplier_id)s AND p.status != 'Cancelled'
                            AND p.payment_date_ad BETWEEN %(date_from)s AND %(date_to)s), 0) AS total_payments,
                COALESCE((SELECT SUM(grand_total) FROM purchase_return
                          WHERE supplier_id = %(supplier_id)s AND status = 'Posted'
                            AND settlement_mode = 'Adjust Against Payable'
                            AND return_date_ad BETWEEN %(date_from)s AND %(date_to)s), 0) AS total_adjustments
        """
        row = self._executor.run(sql, {"supplier_id": supplier_id, "date_from": date_from, "date_to": date_to})[0]
        expected_closing = opening_balance + float(row["total_purchases"]) - float(row["total_payments"]) - float(row["total_adjustments"])
        outstanding_sql = """
            SELECT COALESCE(SUM(pi.grand_total
                - COALESCE(pa_sum.total_allocated, 0) - COALESCE(pr_sum.total_adjusted, 0)), 0) AS actual_outstanding
            FROM purchase_invoice pi
            LEFT JOIN (SELECT pa.purchase_invoice_id, SUM(pa.allocated_amount) AS total_allocated
                       FROM payment_allocation pa JOIN payment p ON p.payment_id = pa.payment_id
                       WHERE p.status != 'Cancelled' GROUP BY pa.purchase_invoice_id) pa_sum
                ON pa_sum.purchase_invoice_id = pi.purchase_invoice_id
            LEFT JOIN (SELECT purchase_invoice_id, SUM(grand_total) AS total_adjusted FROM purchase_return
                       WHERE settlement_mode = 'Adjust Against Payable' AND status != 'Cancelled'
                       GROUP BY purchase_invoice_id) pr_sum ON pr_sum.purchase_invoice_id = pi.purchase_invoice_id
            WHERE pi.supplier_id = %(supplier_id)s AND pi.status = 'Posted';
        """
        actual_row = self._executor.run(outstanding_sql, {"supplier_id": supplier_id})[0]
        actual_closing = float(actual_row["actual_outstanding"])
        if round(expected_closing, 2) != round(actual_closing, 2):
            return {"check": "Payable", "supplier_id": supplier_id, "expected_closing": expected_closing,
                    "actual_closing": actual_closing, "difference": round(expected_closing - actual_closing, 2)}
        return None

    # ------------------------------------------------------------------ #
    # EXPORT METADATA
    # ------------------------------------------------------------------ #
    def build_export_metadata(self, result: ReportResultDTO, company_name: str, branch_name: str,
                               generated_by_name: str) -> dict[str, Any]:
        """
        Builds the confirmed export metadata block (Company/Branch/
        Report Name/Date Range/Generated By/Generated At/Filters Used).
        Actual PDF/Excel FILE generation reuses the project's locked
        tech stack (ReportLab for PDF, openpyxl for Excel) via a shared
        utility already used by other print/export features elsewhere
        in the app -- this method only assembles the metadata dict that
        utility stamps onto the output, it does not render anything
        itself.
        """
        return {
            "company_name": company_name,
            "branch_name": branch_name,
            "report_name": result.report_name,
            "date_range": f"{result.filters_used.get('date_from', 'N/A')} to {result.filters_used.get('date_to', 'N/A')}",
            "generated_by": generated_by_name,
            "generated_at": result.generated_at.isoformat(),
            "filters_used": result.filters_used,
        }